from __future__ import annotations

import fnmatch
import hashlib
import json
import logging
import os
import re
import tempfile
from collections import defaultdict
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import asdict
from functools import partial
from pathlib import Path

from .cards import build_research_card, write_research_card
from .chunker import chunk_sections
from .config import AppConfig
from .curated_index import (
    CatalogRecord,
    CuratedIndex,
    normalize_record_id,
    parse_curated_markdown,
)
from .database import (
    CORPUS_SNAPSHOT_COMPLETE_KEY,
    CORPUS_SOURCE_MANIFEST_KEY,
    CorpusDatabase,
)
from .embeddings import (
    EmbeddingProvider,
    create_embedding_provider,
    embedding_provider_identity,
)
from .extract import ExtractorChain, extract_markdown_reference
from .ids import sha256_file, stable_paper_id, unique_paper_id
from .models import IngestFailure, IngestReport, Paper, SourceDocument
from .parser import parse_sections

LOGGER = logging.getLogger(__name__)
YEAR_RE = re.compile(r"(?<!\d)((?:19|20)\d{2})(?!\d)")
ATX_HEADING_RE = re.compile(r"^ {0,3}#{1,6}[ \t]+(.+?)[ \t]*#*[ \t]*$")
BOLD_ABSTRACT_RE = re.compile(
    r"^\s*(?:\*\*|__)\s*(?:abstract|summary)\s*(?:\*\*|__)"
    r"\s*(?:(?::|[.\-–—])\s*)?(.*)$",
    re.I,
)
PLAIN_ABSTRACT_RE = re.compile(
    r"^\s*(?:abstract|summary)\s*(?:(?::|[.\-–—])\s*(.*))?$",
    re.I,
)
GENERIC_TITLES = {
    "",
    "untitled",
    "document",
    "article",
    "paper",
    "full text",
    "microsoft word",
}
NON_PAPER_MARKDOWN = {
    "agents.md",
    "index.md",
    "jon_download_list.md",
    "readme.md",
    "research_mcp.md",
}


def _relative(path: Path, root: Path) -> str:
    try:
        return path.resolve().relative_to(root.resolve()).as_posix()
    except ValueError:
        return str(path.resolve())


def _stage_text(path: Path, text: str) -> Path:
    """Write a same-filesystem staging file without replacing the published artifact."""

    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(
        prefix=f".{path.name}.",
        suffix=".tmp",
        dir=path.parent,
    )
    staged = Path(temporary)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
    except Exception:
        staged.unlink(missing_ok=True)
        raise
    return staged


def _publish_staged_file(source: Path, target: Path) -> None:
    os.replace(source, target)


def _assert_markdown_target_safe(
    path: Path,
    paper_id: str,
    markdown: str,
    database: CorpusDatabase,
    root: Path,
    canonical_source_paths: set[str],
) -> None:
    if not path.exists():
        return
    if _relative(path, root) in canonical_source_paths:
        raise RuntimeError(
            f"refusing to overwrite canonical source Markdown with generated extraction: {path}"
        )
    existing = database.get_paper(paper_id)
    if existing is not None and existing.source_kind == "pdf" and existing.markdown_path:
        prior = Path(existing.markdown_path)
        if not prior.is_absolute():
            prior = root / prior
        if prior.resolve() == path.resolve():
            return
    try:
        if path.read_text(encoding="utf-8") == markdown:
            return
    except (OSError, UnicodeError):
        pass
    raise RuntimeError(f"refusing to overwrite pre-existing non-generated Markdown target: {path}")


def _assert_card_target_safe(
    path: Path,
    paper_id: str,
    database: CorpusDatabase | None = None,
) -> None:
    if not path.exists():
        return
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError):
        payload = None
    if payload is None and database is not None and database.get_paper(paper_id) is not None:
        return
    if (
        isinstance(payload, dict)
        and payload.get("generated_by") == "papers-mcp"
        and payload.get("paper_id") == paper_id
    ):
        return
    # Accept cards generated by releases before the explicit marker was added.
    if (
        isinstance(payload, dict)
        and payload.get("paper_id") == paper_id
        and "Original paper text remains authoritative" in str(payload.get("authority", ""))
    ):
        return
    raise RuntimeError(f"refusing to overwrite pre-existing non-generated card: {path}")


def _remove_generated_artifacts(
    config: AppConfig,
    paper: Paper,
    database: CorpusDatabase,
    current_source_paths: set[str],
) -> None:
    card_path = config.paths.cards / f"{paper.id}.json"
    try:
        _assert_card_target_safe(card_path, paper.id, database)
    except RuntimeError:
        pass
    else:
        card_path.unlink(missing_ok=True)
    if paper.source_kind != "pdf" or not paper.markdown_path:
        return
    candidate = Path(paper.markdown_path)
    if not candidate.is_absolute():
        candidate = config.paths.root / candidate
    try:
        candidate.resolve().relative_to(config.paths.generated_markdown.resolve())
    except ValueError:
        return
    source = Path(paper.source_path)
    if not source.is_absolute():
        source = config.paths.root / source
    if candidate.resolve() == source.resolve():
        return
    if _relative(candidate, config.paths.root) in current_source_paths:
        return
    for current_paper in database.list_papers():
        for alias in database.source_aliases(current_paper.id):
            alias_path = Path(alias["source_path"])
            if not alias_path.is_absolute():
                alias_path = config.paths.root / alias_path
            if alias_path.resolve() == candidate.resolve():
                return
    recorded_hash = database.get_meta(_generated_markdown_hash_key(paper.id))
    if recorded_hash is None:
        return
    try:
        if sha256_file(candidate) != recorded_hash:
            return
    except OSError:
        return
    candidate.unlink(missing_ok=True)
    database.delete_meta(_generated_markdown_hash_key(paper.id))


def _excluded(path: Path, root: Path, exclusions: Sequence[str]) -> bool:
    relative = _relative(path, root)
    if Path(relative).is_absolute():
        return False
    for exclusion in exclusions:
        normalized = exclusion.strip("/")
        if relative == normalized or relative.startswith(f"{normalized}/"):
            return True
    return False


def _discover_pdfs_with_errors(config: AppConfig) -> tuple[list[Path], list[tuple[Path, str]]]:
    found: dict[str, Path] = {}
    errors: list[tuple[Path, str]] = []
    for root in config.paths.pdf_roots:
        if not root.exists():
            continue

        def record_error(exc: OSError, source_root: Path = root) -> None:
            failed_path = Path(exc.filename) if exc.filename else source_root
            errors.append((failed_path, str(exc)))

        for directory, directory_names, filenames in os.walk(
            root,
            topdown=True,
            onerror=record_error,
            followlinks=False,
        ):
            directory_path = Path(directory)
            directory_names[:] = [
                name
                for name in directory_names
                if not _excluded(
                    directory_path / name,
                    config.paths.root,
                    config.paths.exclude_dirs,
                )
            ]
            for filename in filenames:
                path = directory_path / filename
                if path.suffix.casefold() != ".pdf" or _excluded(
                    path,
                    config.paths.root,
                    config.paths.exclude_dirs,
                ):
                    continue
                try:
                    if path.is_file():
                        found[str(path.resolve())] = path.resolve()
                except OSError as exc:
                    errors.append((path, str(exc)))
    paths = sorted(found.values(), key=lambda item: _relative(item, config.paths.root).casefold())
    return paths, errors


def _discover_pdfs(config: AppConfig) -> list[Path]:
    paths, _ = _discover_pdfs_with_errors(config)
    return paths


def _discover_markdown_with_errors(
    config: AppConfig,
    curated: CuratedIndex,
) -> tuple[list[Path], list[tuple[Path, str]]]:
    if not config.paths.markdown_sources_from_index:
        return [], []
    names = {
        artifact
        for artifacts in [
            *(record.artifacts for record in curated.records),
            *(entry.artifacts for entry in curated.entries),
        ]
        for artifact in artifacts
        if artifact.casefold().endswith(".md")
        and Path(artifact).name.casefold() not in NON_PAPER_MARKDOWN
    }
    roots = list(dict.fromkeys([config.paths.root, *config.paths.pdf_roots]))
    available: dict[str, Path] = {}
    errors: list[tuple[Path, str]] = []
    for root in roots:

        def record_error(exc: OSError, source_root: Path = root) -> None:
            failed_path = Path(exc.filename) if exc.filename else source_root
            errors.append((failed_path, str(exc)))

        for directory, directory_names, filenames in os.walk(
            root,
            topdown=True,
            onerror=record_error,
            followlinks=False,
        ):
            directory_path = Path(directory)
            directory_names[:] = [
                name
                for name in directory_names
                if not _excluded(
                    directory_path / name,
                    config.paths.root,
                    config.paths.exclude_dirs,
                )
            ]
            for filename in filenames:
                path = directory_path / filename
                if path.suffix.casefold() != ".md" or _excluded(
                    path,
                    config.paths.root,
                    config.paths.exclude_dirs,
                ):
                    continue
                try:
                    if path.is_file():
                        available[str(path.resolve())] = path.resolve()
                except OSError as exc:
                    errors.append((path, str(exc)))

    found: dict[str, Path] = {}
    for name in names:
        selected: Path | None = None
        basename_candidates = {
            key: candidate
            for key, candidate in available.items()
            if candidate.name.casefold() == Path(name).name.casefold()
        }
        is_bare_basename = len(Path(name).parts) == 1
        if not is_bare_basename:
            for root in roots:
                direct = (root / name).resolve()
                if str(direct) in available:
                    selected = available[str(direct)]
                    break
            if selected is None:
                casefold_matches: dict[str, Path] = {}
                for root in roots:
                    resolved_root = root.resolve()
                    for key, candidate in available.items():
                        try:
                            relative_candidate = candidate.relative_to(resolved_root).as_posix()
                        except ValueError:
                            continue
                        if relative_candidate.casefold() == name.casefold():
                            casefold_matches[key] = candidate
                if len(casefold_matches) == 1:
                    selected = next(iter(casefold_matches.values()))
        if selected is None and len(basename_candidates) == 1:
            selected = next(iter(basename_candidates.values()))
        if selected is not None:
            found[str(selected)] = selected
    paths = sorted(found.values(), key=lambda item: _relative(item, config.paths.root).casefold())
    unique_errors = list(dict.fromkeys((str(path.resolve()), error) for path, error in errors))
    return paths, [(Path(path), error) for path, error in unique_errors]


def _discover_markdown(config: AppConfig, curated: CuratedIndex) -> list[Path]:
    paths, _ = _discover_markdown_with_errors(config, curated)
    return paths


def discover_sources(config: AppConfig, curated: CuratedIndex) -> list[SourceDocument]:
    return [
        SourceDocument(path, source_kind, sha256_file(path))
        for path, source_kind in _discovered_source_locations(config, curated)
    ]


def build_source_manifest(
    config: AppConfig,
    index_hash: str,
    sources: Sequence[SourceDocument],
) -> dict[str, object]:
    """Describe every source observed by a clean, unfiltered corpus scan."""

    return {
        "format": 1,
        "human_index": {
            "path": _relative(config.paths.human_index, config.paths.root),
            "sha256": index_hash,
        },
        "sources": [
            {
                "path": _relative(source.path, config.paths.root),
                "kind": source.source_kind,
                "sha256": source.content_hash,
            }
            for source in sorted(
                sources,
                key=lambda item: (
                    _relative(item.path, config.paths.root).casefold(),
                    item.source_kind,
                ),
            )
        ],
    }


def _discovered_source_locations(
    config: AppConfig,
    curated: CuratedIndex,
    *,
    pdfs: Sequence[Path] | None = None,
    markdown: Sequence[Path] | None = None,
) -> list[tuple[Path, str]]:
    locations = [
        *((path, "pdf") for path in (pdfs if pdfs is not None else _discover_pdfs(config))),
        *(
            (path, "markdown_reference")
            for path in (markdown if markdown is not None else _discover_markdown(config, curated))
        ),
    ]
    unique = {
        (str(path.resolve()), source_kind): (path.resolve(), source_kind)
        for path, source_kind in locations
    }
    return sorted(
        unique.values(),
        key=lambda item: _relative(item[0], config.paths.root).casefold(),
    )


def _deduplicate_sources(
    sources: Sequence[SourceDocument],
    root: Path,
) -> tuple[list[SourceDocument], dict[str, list[SourceDocument]]]:
    by_hash: dict[str, list[SourceDocument]] = defaultdict(list)
    for source in sources:
        by_hash[source.content_hash].append(source)
    canonical: list[SourceDocument] = []
    aliases: dict[str, list[SourceDocument]] = {}
    for content_hash, group in by_hash.items():
        ordered = sorted(
            group,
            key=lambda source: (
                len(Path(_relative(source.path, root)).parts),
                _relative(source.path, root).casefold(),
            ),
        )
        canonical.append(ordered[0])
        aliases[content_hash] = ordered[1:]
    canonical.sort(key=lambda source: _relative(source.path, root).casefold())
    return canonical, aliases


def _artifact_key_for_source(
    curated: CuratedIndex,
    source: SourceDocument,
    root: Path,
    sources: Sequence[SourceDocument] | None = None,
    *,
    artifact_roots: Sequence[Path] = (),
) -> str:
    keys = set(curated.artifact_to_paper_id)
    referenced = {artifact for record in curated.records for artifact in record.artifacts} | {
        artifact for entry in curated.entries for artifact in entry.artifacts
    }
    inventory = sources or (source,)

    def relative_candidates(path: Path) -> list[str]:
        candidates: list[str] = []
        for candidate_root in dict.fromkeys((root, *artifact_roots)):
            try:
                relative_path = path.resolve().relative_to(candidate_root.resolve()).as_posix()
            except ValueError:
                continue
            if relative_path not in candidates:
                candidates.append(relative_path)
        return candidates or [_relative(path, root)]

    relative = _relative(source.path, root)
    source_candidates = relative_candidates(source.path)
    candidate_owners: dict[str, set[str]] = defaultdict(set)
    for item in inventory:
        for candidate in relative_candidates(item.path):
            candidate_owners[candidate.casefold()].add(str(item.path.resolve()))
    basename_matches = {
        str(item.path.resolve())
        for item in inventory
        if item.path.name.casefold() == source.path.name.casefold()
    }
    basename_is_unique = len(basename_matches) == 1
    is_bare_basename = len(Path(relative).parts) == 1

    def exact_match(candidates: set[str]) -> str | None:
        for source_candidate in source_candidates:
            if len(Path(source_candidate).parts) == 1 and not basename_is_unique:
                continue
            if len(candidate_owners[source_candidate.casefold()]) != 1:
                continue
            if source_candidate in candidates:
                return source_candidate
            matches = sorted(
                (
                    candidate
                    for candidate in candidates
                    if candidate.casefold() == source_candidate.casefold()
                ),
                key=lambda candidate: (candidate.casefold(), candidate),
            )
            if len(matches) == 1:
                return matches[0]
        return None

    matched = exact_match(referenced)
    if matched is not None:
        return matched

    # A bare filename cannot distinguish a root-level source from another source
    # with the same basename. Use a private, non-normalized key so reconciliation
    # cannot accidentally overwrite the curated bare-filename alias.
    if not basename_is_unique:
        return f"./{relative}" if is_bare_basename else relative

    def unique_basename_match(candidates: set[str]) -> str | None:
        matches = sorted(
            (
                candidate
                for candidate in candidates
                if Path(candidate).name.casefold() == source.path.name.casefold()
            ),
            key=lambda candidate: (candidate.casefold(), candidate),
        )
        return matches[0] if len(matches) == 1 else None

    matched = unique_basename_match(referenced)
    if matched is not None:
        return matched
    matched = exact_match(keys)
    if matched is not None:
        return matched
    matched = unique_basename_match(keys)
    return matched if matched is not None else relative


def _resolve_curated_artifact_identities(
    curated: CuratedIndex,
    sources: Sequence[SourceDocument],
    root: Path,
    database: CorpusDatabase,
    *,
    source_inventory: Sequence[SourceDocument] | None = None,
    artifact_roots: Sequence[Path] = (),
) -> None:
    """Split distinct works on multi-artifact rows and reunify byte-identical aliases."""

    inventory = source_inventory or sources

    for record in curated.records:
        if len(record.artifacts) > 1:
            for artifact in record.artifacts:
                curated.artifact_to_paper_id[artifact] = normalize_record_id(Path(artifact).stem)

    sources_by_basename: dict[str, list[SourceDocument]] = defaultdict(list)
    for source in inventory:
        sources_by_basename[source.path.name.casefold()].append(source)
    ambiguous_basenames = {
        basename
        for basename, matches in sources_by_basename.items()
        if len({str(source.path.resolve()) for source in matches}) > 1
    }
    for artifact in list(curated.artifact_to_paper_id):
        if len(Path(artifact).parts) == 1 and Path(artifact).name.casefold() in ambiguous_basenames:
            curated.artifact_to_paper_id.pop(artifact)

    by_hash: dict[str, list[SourceDocument]] = defaultdict(list)
    for source in sources:
        by_hash[source.content_hash].append(source)
    for group in by_hash.values():
        canonical = min(
            group,
            key=lambda source: (
                len(Path(_relative(source.path, root)).parts),
                _relative(source.path, root).casefold(),
            ),
        )
        existing_ids = []
        for source in group:
            source_path = _relative(source.path, root)
            owner = database.find_paper_by_source(source_path)
            if owner is not None and owner.content_hash == source.content_hash:
                existing_ids.append(owner.id)
        canonical_key = _artifact_key_for_source(
            curated,
            canonical,
            root,
            inventory,
            artifact_roots=artifact_roots,
        )
        paper_id = (
            existing_ids[0]
            if existing_ids
            else curated.artifact_to_paper_id.get(
                canonical_key,
                normalize_record_id(canonical.path.stem),
            )
        )
        for source in group:
            curated.artifact_to_paper_id[
                _artifact_key_for_source(
                    curated,
                    source,
                    root,
                    inventory,
                    artifact_roots=artifact_roots,
                )
            ] = paper_id

    _refresh_curated_entry_links(curated)


def _refresh_curated_entry_links(
    curated: CuratedIndex,
    record_id_remap: Mapping[str, Sequence[str]] | None = None,
) -> None:
    records_by_line = {record.source_line: record for record in curated.records}
    for entry in curated.entries:
        record = records_by_line.get(entry.source_line)
        artifacts = record.artifacts if record is not None else entry.artifacts
        if not artifacts:
            if record_id_remap:
                provisional_ids = entry.linked_paper_ids or (
                    [record.record_id] if record is not None else []
                )
                entry.linked_paper_ids = list(
                    dict.fromkeys(
                        actual_id
                        for provisional_id in provisional_ids
                        for actual_id in record_id_remap.get(
                            provisional_id,
                            (provisional_id,),
                        )
                    )
                )
            continue
        entry.linked_paper_ids = list(
            dict.fromkeys(
                curated.artifact_to_paper_id[artifact]
                for artifact in artifacts
                if artifact in curated.artifact_to_paper_id
            )
        )


def _relink_curated_to_stored_papers(
    curated: CuratedIndex,
    sources: Sequence[SourceDocument],
    root: Path,
    database: CorpusDatabase,
    catalog_artifact_to_record_id: Mapping[str, str],
    *,
    artifact_roots: Sequence[Path] = (),
) -> None:
    """Make curated artifact links follow the IDs actually assigned during ingestion."""

    actual_ids_by_provisional: dict[str, list[str]] = defaultdict(list)
    for source in sources:
        source_path = _relative(source.path, root)
        owner = database.find_paper_by_source(source_path)
        if owner is None:
            continue
        artifact = _artifact_key_for_source(
            curated,
            source,
            root,
            sources,
            artifact_roots=artifact_roots,
        )
        provisional_id = catalog_artifact_to_record_id.get(artifact)
        if provisional_id is not None:
            actual_ids_by_provisional[provisional_id].append(owner.id)
        curated.artifact_to_paper_id[artifact] = owner.id
    _refresh_curated_entry_links(
        curated,
        {
            provisional_id: list(dict.fromkeys(actual_ids))
            for provisional_id, actual_ids in actual_ids_by_provisional.items()
        },
    )


def _record_lookup(curated: CuratedIndex) -> dict[str, CatalogRecord]:
    return {record.record_id: record for record in curated.records}


def _catalog_title(record: CatalogRecord | None) -> str:
    if record is None:
        return ""
    for key in ("title", "citation", "paper", "name"):
        value = record.fields.get(key, "").strip()
        if value:
            # A citation is still a better human label than a raw filename.
            value = re.sub(r"\s*[·|]\s*.*$", "", value).strip()
            return value
    return ""


def _catalog_authors(record: CatalogRecord | None) -> list[str]:
    if record is None:
        return []
    for key, value in record.fields.items():
        if "citation" not in key.casefold():
            continue
        year = re.search(r"\((?:19|20)\d{2}\)", value)
        if year is None:
            continue
        prefix = re.sub(r"[`*_~]", "", value[: year.start()]).strip(" ,;·")
        if not prefix:
            continue
        authors = [
            item.strip()
            for item in re.split(r"\s*(?:&|\band\b|,)\s*", prefix, flags=re.I)
            if item.strip()
        ]
        if authors:
            return authors
    return []


def _usable_authors(authors: Sequence[str]) -> bool:
    cleaned = [" ".join(author.split()) for author in authors if author.strip()]
    if not cleaned:
        return False
    joined = " ".join(cleaned).casefold()
    if any(
        marker in joined
        for marker in (
            "microsoft word",
            "adobe acrobat",
            "anonymous",
            "unknown author",
        )
    ):
        return False
    if len(cleaned) == 1:
        value = cleaned[0]
        letters = "".join(character for character in value if character.isalpha())
        if len(letters) < 4 or (value == value.casefold() and " " not in value.strip()):
            return False
    return True


def _usable_title(value: str, source: Path) -> bool:
    normalized = " ".join(value.casefold().split())
    if normalized in GENERIC_TITLES or len(normalized) < 4:
        return False
    if normalized == source.stem.casefold() or normalized.startswith("microsoft word"):
        return False
    # Broken PDF metadata and equation fragments are common title values. A
    # filename-derived title is more useful than fragments such as "(E,,) becomes".
    if len(re.findall(r"[^\W\d_]{2,}", value, flags=re.UNICODE)) < 3:
        return False
    return True


def _fallback_title(source: Path) -> str:
    return re.sub(r"[_-]+", " ", source.stem).strip().title()


def _extract_abstract(markdown: str) -> str:
    lines = markdown.replace("\r\n", "\n").replace("\r", "\n").splitlines()
    collected: list[str] = []
    collecting = False
    for line in lines:
        heading_match = ATX_HEADING_RE.match(line)
        if heading_match is not None:
            if collecting:
                break
            label = re.sub(r"[`*_~]", "", heading_match.group(1))
            label = re.sub(r"\s+\{#[^}]+}\s*$", "", label).strip(" :.–—-")
            if label.casefold() in {"abstract", "summary"}:
                collecting = True
            continue

        if not collecting:
            match = BOLD_ABSTRACT_RE.match(line) or PLAIN_ABSTRACT_RE.match(line)
            if match is None:
                continue
            collecting = True
            inline = (match.group(1) or "").strip()
            if inline:
                collected.append(inline)
            continue

        collected.append(line)

    value = "\n".join(collected)
    value = re.sub(r"<!--\s*page\s*:\s*\d+\s*-->", "", value, flags=re.I)
    return value.strip()[:12000]


def contextual_paper_text(paper: Paper, headings: Iterable[str], notes: Iterable[str]) -> str:
    return "\n\n".join(
        part
        for part in [
            f"DOCUMENT:\n{paper.title}",
            f"AUTHORS:\n{', '.join(paper.authors)}" if paper.authors else "",
            f"ABSTRACT:\n{paper.abstract}" if paper.abstract else "",
            "SECTIONS:\n" + "\n".join(headings),
            "CURATED RESEARCH NOTES:\n" + "\n".join(notes),
        ]
        if part
    )


def contextual_section_text(title: str, heading_path: str, text: str) -> str:
    return f"DOCUMENT:\n{title}\n\nSECTION:\n{heading_path}\n\nCONTENT:\n{text}"


def _provider_identity(provider: EmbeddingProvider, dimensions: int) -> tuple[str, str]:
    return embedding_provider_identity(provider, dimensions)


def _stable_digest(value: object) -> str:
    encoded = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(encoded.encode("utf-8")).hexdigest()


def _embedding_state_key(paper_id: str) -> str:
    return f"paper_embedding_state:{paper_id}"


def _generated_markdown_hash_key(paper_id: str) -> str:
    return f"generated_markdown_hash:{paper_id}"


CURATED_EMBEDDING_STATE_KEY = "curated_embedding_state"


class CorpusIngestor:
    def __init__(
        self,
        config: AppConfig,
        database: CorpusDatabase,
        *,
        embedding: EmbeddingProvider | None = None,
        extractor: ExtractorChain | None = None,
    ) -> None:
        self.config = config
        self.database = database
        self.embedding = embedding or create_embedding_provider(
            config.embedding,
            config.resources,
        )
        self.extractor = extractor or ExtractorChain.from_config(
            config.extraction,
            config.resources,
        )

    def _embedding_signature(self) -> str:
        return _stable_digest(asdict(self.config.embedding))

    @staticmethod
    def _notes_signature(notes: Sequence[str]) -> str:
        return _stable_digest(list(notes))

    def _embedding_is_current(self, paper: Paper, notes: Sequence[str]) -> bool:
        raw = self.database.get_meta(_embedding_state_key(paper.id))
        if raw is None:
            return False
        try:
            state = json.loads(raw)
        except (TypeError, json.JSONDecodeError):
            return False
        if not isinstance(state, dict):
            return False
        fingerprint = state.get("model_fingerprint")
        model_name = state.get("model_name")
        configured_backend = self.config.embedding.backend.strip().lower().replace("-", "_")
        if configured_backend not in {"hash", "deterministic_hash"} and str(model_name).startswith(
            "hash-v1"
        ):
            # Probe the lazy provider once per run. If production recovered,
            # upgrade the fallback vectors; if it did not, retain the complete
            # fallback set instead of re-hashing every unchanged paper.
            if not getattr(self.embedding, "is_loaded", False):
                self.embedding.embed_query("academic retrieval backend readiness probe")
            if getattr(self.embedding, "active_backend", configured_backend) != "hash":
                return False
        if getattr(self.embedding, "is_loaded", False):
            active_is_hash = getattr(self.embedding, "active_backend", configured_backend) == "hash"
            stored_is_hash = str(model_name).startswith("hash-v1")
            if active_is_hash != stored_is_hash:
                return False
        return bool(
            isinstance(fingerprint, str)
            and state.get("content_hash") == paper.content_hash
            and state.get("config_signature") == self._embedding_signature()
            and state.get("notes_signature") == self._notes_signature(notes)
            and self.database.paper_embeddings_complete(paper.id, fingerprint)
        )

    def _record_embedding_state(
        self,
        paper: Paper,
        notes: Sequence[str],
        *,
        model_name: str,
        model_fingerprint: str,
    ) -> None:
        state = {
            "content_hash": paper.content_hash,
            "config_signature": self._embedding_signature(),
            "notes_signature": self._notes_signature(notes),
            "model_name": model_name,
            "model_fingerprint": model_fingerprint,
        }
        self.database.set_meta(
            _embedding_state_key(paper.id),
            json.dumps(state, ensure_ascii=False, sort_keys=True),
        )

    def _curated_embeddings_are_current(self, index_hash: str) -> bool:
        raw = self.database.get_meta(CURATED_EMBEDDING_STATE_KEY)
        if raw is None:
            return False
        try:
            state = json.loads(raw)
        except (TypeError, json.JSONDecodeError):
            return False
        if not isinstance(state, dict):
            return False
        fingerprint = state.get("model_fingerprint")
        model_name = state.get("model_name")
        configured_backend = self.config.embedding.backend.strip().lower().replace("-", "_")
        if configured_backend not in {"hash", "deterministic_hash"} and str(model_name).startswith(
            "hash-v1"
        ):
            if not getattr(self.embedding, "is_loaded", False):
                self.embedding.embed_query("academic retrieval backend readiness probe")
            if getattr(self.embedding, "active_backend", configured_backend) != "hash":
                return False
        if getattr(self.embedding, "is_loaded", False):
            active_is_hash = getattr(self.embedding, "active_backend", configured_backend) == "hash"
            stored_is_hash = str(model_name).startswith("hash-v1")
            if active_is_hash != stored_is_hash:
                return False
        return bool(
            isinstance(fingerprint, str)
            and state.get("index_hash") == index_hash
            and state.get("config_signature") == self._embedding_signature()
            and self.database.curated_embeddings_complete(fingerprint)
        )

    def _record_curated_embedding_state(
        self,
        index_hash: str,
        *,
        model_name: str,
        model_fingerprint: str,
    ) -> None:
        state = {
            "index_hash": index_hash,
            "config_signature": self._embedding_signature(),
            "model_name": model_name,
            "model_fingerprint": model_fingerprint,
        }
        self.database.set_meta(
            CURATED_EMBEDDING_STATE_KEY,
            json.dumps(state, ensure_ascii=False, sort_keys=True),
        )

    def _embed_paper(
        self,
        paper: Paper,
        sections,
        chunks,
        notes: list[str],
        *,
        protected_production_fingerprint: str | None = None,
    ) -> tuple[str, str]:
        model_name, fingerprint, vectors = self._prepare_paper_embeddings(
            paper,
            sections,
            chunks,
            notes,
        )
        self._guard_production_embeddings(
            model_name,
            fingerprint,
            protected_production_fingerprint,
        )
        rows = self._paper_embedding_rows(paper, sections, chunks, vectors)
        self.database.replace_embeddings_for_paper(
            paper.id,
            rows,
            model_name=model_name,
            model_fingerprint=fingerprint,
        )
        return model_name, fingerprint

    def _prepare_paper_embeddings(
        self,
        paper: Paper,
        sections,
        chunks,
        notes: Sequence[str],
    ) -> tuple[str, str, list[Sequence[float]]]:
        texts = [contextual_paper_text(paper, (item.heading_path for item in sections), notes)]
        texts.extend(
            contextual_section_text(paper.title, item.heading_path, item.text) for item in sections
        )
        texts.extend(
            contextual_section_text(paper.title, item.heading_path, item.text) for item in chunks
        )
        vectors = self.embedding.embed_documents(texts)
        if len(vectors) != len(texts) or not vectors:
            raise RuntimeError("embedding provider returned an incomplete paper batch")
        dimensions = len(vectors[0])
        if dimensions <= 0 or any(len(vector) != dimensions for vector in vectors):
            raise RuntimeError("embedding provider returned inconsistent paper dimensions")
        model_name, fingerprint = _provider_identity(self.embedding, len(vectors[0]))
        return model_name, fingerprint, vectors

    @staticmethod
    def _guard_production_embeddings(
        model_name: str,
        fingerprint: str,
        protected_production_fingerprint: str | None,
    ) -> None:
        if (
            protected_production_fingerprint is not None
            and fingerprint != protected_production_fingerprint
            and model_name.startswith("hash-v1:")
        ):
            raise RuntimeError(
                "active embedding provider degraded to deterministic hash; preserved the "
                "existing production vector corpus instead of replacing it"
            )

    @staticmethod
    def _paper_embedding_rows(
        paper: Paper,
        sections,
        chunks,
        vectors: Sequence[Sequence[float]],
    ) -> list[tuple[str, str | int, Sequence[float]]]:
        rows: list[tuple[str, str | int, Sequence[float]]] = [("paper", paper.id, vectors[0])]
        cursor = 1
        for index, item in enumerate(sections):
            if item.id is None:
                raise RuntimeError("cannot store an embedding for an unpersisted section")
            rows.append(("section", item.id, vectors[cursor + index]))
        cursor += len(sections)
        for index, item in enumerate(chunks):
            if item.id is None:
                raise RuntimeError("cannot store an embedding for an unpersisted chunk")
            rows.append(("chunk", item.id, vectors[cursor + index]))
        return rows

    def _commit_prepared_paper_artifacts(
        self,
        paper: Paper,
        sections,
        chunks,
        notes: Sequence[str],
        prepared_embedding: tuple[str, str, list[Sequence[float]]] | None,
        staged_markdown: Path | None,
        generated_path: Path | None,
        generated_markdown: str,
    ) -> None:
        """Commit vectors and a staged derivative inside the paper transaction."""

        if prepared_embedding is not None:
            model_name, fingerprint, vectors = prepared_embedding
            rows = self._paper_embedding_rows(paper, sections, chunks, vectors)
            self.database.replace_embeddings_for_paper(
                paper.id,
                rows,
                model_name=model_name,
                model_fingerprint=fingerprint,
            )
            self._record_embedding_state(
                paper,
                notes,
                model_name=model_name,
                model_fingerprint=fingerprint,
            )
        if staged_markdown is not None and generated_path is not None:
            self.database.set_meta(
                _generated_markdown_hash_key(paper.id),
                hashlib.sha256(generated_markdown.encode("utf-8")).hexdigest(),
            )
            _publish_staged_file(staged_markdown, generated_path)

    def _embed_curated(self, entries) -> tuple[str, str] | None:
        prepared = self._prepare_curated_embeddings(entries)
        if prepared is None:
            return None
        model_name, fingerprint, vectors = prepared
        self._store_curated_embeddings(
            entries,
            vectors,
            model_name=model_name,
            model_fingerprint=fingerprint,
        )
        return model_name, fingerprint

    def _prepare_curated_embeddings(
        self,
        entries,
    ) -> tuple[str, str, list[Sequence[float]]] | None:
        ready = [entry for entry in entries if entry.id is not None]
        # Before database insertion the IDs are intentionally absent, but the
        # entry order is already final and can be embedded safely.
        if not ready and entries and all(entry.id is None for entry in entries):
            ready = list(entries)
        if not ready:
            return None
        texts = [
            f"CURATED INDEX PATH:\n{entry.heading_path}\n\nNOTE:\n{entry.text}" for entry in ready
        ]
        vectors = self.embedding.embed_documents(texts)
        if len(vectors) != len(texts) or not vectors:
            raise RuntimeError("embedding provider returned an incomplete curated batch")
        dimensions = len(vectors[0])
        if dimensions <= 0 or any(len(vector) != dimensions for vector in vectors):
            raise RuntimeError("embedding provider returned inconsistent curated dimensions")
        model_name, fingerprint = _provider_identity(self.embedding, len(vectors[0]))
        return model_name, fingerprint, vectors

    def _store_curated_embeddings(
        self,
        entries,
        vectors: Sequence[Sequence[float]],
        *,
        model_name: str,
        model_fingerprint: str,
    ) -> None:
        ready = [entry for entry in entries if entry.id is not None]
        if len(ready) != len(vectors):
            raise RuntimeError("cannot store embeddings for unpersisted curated entries")
        self.database.replace_curated_embeddings(
            [
                (
                    "curated",
                    entry.id,
                    # Resolve provenance from the persisted link table.  Parsed
                    # entries can still contain catalog shorthand IDs that did
                    # not resolve to an ingested paper; storing those values in
                    # embeddings.paper_id makes paper-scoped vector metadata lie.
                    None,
                    vector,
                )
                for entry, vector in zip(ready, vectors, strict=True)
            ],
            model_name=model_name,
            model_fingerprint=model_fingerprint,
        )

    def _commit_curated_artifacts(
        self,
        entries,
        prepared: tuple[str, str, list[Sequence[float]]] | None,
        curated_version: str,
        index_hash: str,
        resolution_signature: str,
    ) -> None:
        if prepared is not None:
            model_name, fingerprint, vectors = prepared
            self._store_curated_embeddings(
                entries,
                vectors,
                model_name=model_name,
                model_fingerprint=fingerprint,
            )
            self._record_curated_embedding_state(
                curated_version,
                model_name=model_name,
                model_fingerprint=fingerprint,
            )
        self.database.set_meta("curated_index_hash", index_hash)
        self.database.set_meta("curated_resolution_signature", resolution_signature)

    def _reconcile_displaced_paper(
        self,
        paper: Paper,
        current_source_hashes: dict[str, str],
        curated: CuratedIndex,
        *,
        require_current_hash: bool = True,
        notes_override: Sequence[str] | None = None,
        uncertain_source_paths: set[str] | None = None,
    ) -> bool:
        """Retire an orphaned record or point it at a remaining live identical source."""

        uncertain_source_paths = uncertain_source_paths or set()
        current = self.database.get_paper(paper.id)
        if current is None:
            return True
        aliases = self.database.source_aliases(paper.id)
        matching_aliases = [
            alias
            for alias in aliases
            if current_source_hashes.get(alias["source_path"]) == current.content_hash
        ]
        uncertain_aliases = [
            alias for alias in aliases if alias["source_path"] in uncertain_source_paths
        ]
        if matching_aliases and not require_current_hash:
            matching_paths = {
                alias["source_path"] for alias in [*matching_aliases, *uncertain_aliases]
            }
            for alias in aliases:
                if alias["source_path"] not in matching_paths:
                    self.database.remove_source_alias(alias["source_path"])
        live_aliases = [
            *matching_aliases,
            *(
                alias
                for alias in uncertain_aliases
                if alias["source_path"] not in {item["source_path"] for item in matching_aliases}
            ),
        ] or ([] if require_current_hash else aliases)
        if not live_aliases:
            if self.database.delete_paper(paper.id):
                _remove_generated_artifacts(
                    self.config,
                    current,
                    self.database,
                    set(current_source_hashes),
                )
                return True
            return False
        live_paths = {alias["source_path"] for alias in live_aliases}
        if current.source_path not in live_paths:
            self.database.repoint_paper_source(paper.id, live_aliases[0]["source_path"])
            current = self.database.get_paper(paper.id) or current
        sections = self.database.get_sections(paper.id)
        card_path = self.config.paths.cards / f"{paper.id}.json"
        _assert_card_target_safe(card_path, paper.id, self.database)
        write_research_card(
            card_path,
            build_research_card(
                current,
                sections,
                list(notes_override) if notes_override is not None else curated.notes_for(paper.id),
            ),
        )
        return False

    def _embedding_state_fingerprint(self, paper_id: str) -> str | None:
        raw = self.database.get_meta(_embedding_state_key(paper_id))
        if raw is None:
            return None
        try:
            state = json.loads(raw)
        except (TypeError, json.JSONDecodeError):
            return None
        fingerprint = state.get("model_fingerprint") if isinstance(state, dict) else None
        return fingerprint if isinstance(fingerprint, str) else None

    def _stored_notes_for(self, paper_id: str) -> list[str]:
        return [
            entry.text
            for entry in self.database.get_curated_entries()
            if paper_id in entry.linked_paper_ids
        ]

    def _curated_state_fingerprint(self) -> str | None:
        raw = self.database.get_meta(CURATED_EMBEDDING_STATE_KEY)
        if raw is None:
            return None
        try:
            state = json.loads(raw)
        except (TypeError, json.JSONDecodeError):
            return None
        fingerprint = state.get("model_fingerprint") if isinstance(state, dict) else None
        return fingerprint if isinstance(fingerprint, str) else None

    def _reconcile_embedding_identity(
        self,
        index_hash: str,
        *,
        protected_production_fingerprint: str | None = None,
    ) -> int:
        """Ensure one active fingerprint completely covers every current hierarchy."""

        papers = self.database.list_papers()
        if not papers:
            return 0
        fingerprints = {
            fingerprint
            for paper in papers
            if (fingerprint := self._embedding_state_fingerprint(paper.id)) is not None
        }
        all_current = all(
            self._embedding_is_current(paper, self._stored_notes_for(paper.id)) for paper in papers
        )
        if (
            all_current
            and len(fingerprints) == 1
            and self.database.corpus_embeddings_complete(next(iter(fingerprints)))
            and self._curated_embeddings_are_current(index_hash)
        ):
            return 0

        probe = self.embedding.embed_query("academic retrieval embedding identity probe")
        target_model_name, target = embedding_provider_identity(self.embedding, len(probe))
        if (
            protected_production_fingerprint is not None
            and target != protected_production_fingerprint
            and target_model_name.startswith("hash-v1:")
        ):
            raise RuntimeError(
                "active embedding provider degraded to deterministic hash; preserved the "
                "existing production vector corpus instead of globally downgrading it"
            )
        refreshed: set[str] = set()
        for _ in range(3):
            identity_changed = False
            for paper in self.database.list_papers():
                notes = self._stored_notes_for(paper.id)
                if self._embedding_state_fingerprint(
                    paper.id
                ) == target and self._embedding_is_current(paper, notes):
                    continue
                sections = self.database.get_sections(paper.id)
                chunks = self.database.get_chunks(paper.id)
                if not sections or not chunks:
                    raise RuntimeError(
                        f"stored hierarchy for {paper.id} is incomplete during embedding reconciliation"
                    )
                model_name, fingerprint = self._embed_paper(
                    paper,
                    sections,
                    chunks,
                    notes,
                    protected_production_fingerprint=protected_production_fingerprint,
                )
                self._record_embedding_state(
                    paper,
                    notes,
                    model_name=model_name,
                    model_fingerprint=fingerprint,
                )
                refreshed.add(paper.id)
                if fingerprint != target:
                    target = fingerprint
                    identity_changed = True
                    break
            if identity_changed:
                continue
            if not (
                self._curated_state_fingerprint() == target
                and self._curated_embeddings_are_current(index_hash)
            ):
                identity = self._embed_curated(self.database.get_curated_entries())
                if identity is not None:
                    model_name, fingerprint = identity
                    self._record_curated_embedding_state(
                        index_hash,
                        model_name=model_name,
                        model_fingerprint=fingerprint,
                    )
                    if fingerprint != target:
                        target = fingerprint
                        continue
            if self.database.corpus_embeddings_complete(target):
                return len(refreshed)
        raise RuntimeError("embedding backend identity did not stabilize after three passes")

    def ingest(
        self,
        *,
        force: bool = False,
        rechunk: bool = False,
        limit: int | None = None,
        patterns: Sequence[str] = (),
        embeddings: bool = True,
    ) -> IngestReport:
        unavailable_roots = [
            path
            for path in self.config.paths.pdf_roots
            if not path.is_dir() or not os.access(path, os.R_OK | os.X_OK)
        ]
        if unavailable_roots:
            rendered = ", ".join(str(path) for path in unavailable_roots)
            raise RuntimeError(
                "configured source roots are missing or unreadable; refusing corpus "
                f"reconciliation: {rendered}"
            )
        self.config.ensure_output_dirs()
        # A crash or deliberately filtered run must not leave `doctor` claiming
        # that every currently discoverable source was processed.
        self.database.set_meta(CORPUS_SNAPSHOT_COMPLETE_KEY, "0")
        production_paper_fingerprints = {
            str(row["model_fingerprint"])
            for row in self.database.paper_embedding_fingerprints()
            if not str(row["model_name"]).startswith("hash-v1:")
        }
        protected_production_fingerprint = next(
            (
                fingerprint
                for paper in self.database.list_papers()
                if (fingerprint := self._embedding_state_fingerprint(paper.id))
                in production_paper_fingerprints
            ),
            next(iter(production_paper_fingerprints), None),
        )
        discovered_pdfs, pdf_discovery_errors = _discover_pdfs_with_errors(self.config)
        known_paths = [_relative(path, self.config.paths.root) for path in discovered_pdfs]
        index_bytes = self.config.paths.human_index.read_bytes()
        index_hash = hashlib.sha256(index_bytes).hexdigest()
        curated = parse_curated_markdown(
            index_bytes.decode("utf-8"),
            known_artifacts=known_paths,
        )
        catalog_artifact_to_record_id = dict(curated.artifact_to_paper_id)
        discovered_markdown, markdown_discovery_errors = _discover_markdown_with_errors(
            self.config,
            curated,
        )
        discovery_errors = [*pdf_discovery_errors, *markdown_discovery_errors]
        source_locations = _discovered_source_locations(
            self.config,
            curated,
            pdfs=discovered_pdfs,
            markdown=discovered_markdown,
        )
        report = IngestReport(found=len(source_locations))
        repaired_provenance = self.database.repair_embedding_provenance()
        if repaired_provenance:
            report.warnings.append(
                f"Repaired provenance for {repaired_provenance} stored embedding row(s)."
            )
        removed_empty_chunks = self.database.remove_empty_chunks()
        if removed_empty_chunks:
            report.warnings.append(
                f"Removed {removed_empty_chunks} marker-only retrieval chunk(s)."
            )
        sources: list[SourceDocument] = []
        failed_source_stubs: list[SourceDocument] = []
        observed_source_paths = {
            _relative(path, self.config.paths.root) for path, _ in source_locations
        }
        for failed_path, error in discovery_errors:
            source_path = _relative(failed_path, self.config.paths.root)
            LOGGER.error("Failed to scan source directory %s: %s", source_path, error)
            report.failed += 1
            failure = IngestFailure(
                source_path=source_path,
                stage="source_discovery",
                error=error,
            )
            report.failures.append(failure)
            self.database.record_failure(source_path, "source_discovery", error)
        for path, source_kind in source_locations:
            source_path = _relative(path, self.config.paths.root)
            try:
                sources.append(SourceDocument(path, source_kind, sha256_file(path)))
            except Exception as exc:
                if isinstance(exc, MemoryError):
                    raise
                LOGGER.exception("Failed to hash source %s", source_path)
                report.failed += 1
                failure = IngestFailure(
                    source_path=source_path,
                    stage="source_hash",
                    error=str(exc),
                )
                report.failures.append(failure)
                failed_source_stubs.append(SourceDocument(path, source_kind, ""))
                self.database.record_failure(
                    source_path,
                    "source_hash",
                    str(exc),
                )
        source_inventory = [*sources, *failed_source_stubs]
        _resolve_curated_artifact_identities(
            curated,
            sources,
            self.config.paths.root,
            self.database,
            source_inventory=source_inventory,
            artifact_roots=self.config.paths.pdf_roots,
        )
        current_source_hashes = {
            _relative(item.path, self.config.paths.root): item.content_hash for item in sources
        }
        source_snapshot_incomplete = bool(discovery_errors or failed_source_stubs)
        uncertain_source_paths = {
            _relative(item.path, self.config.paths.root) for item in failed_source_stubs
        }
        if discovery_errors:
            uncertain_source_paths.update(
                alias["source_path"]
                for paper in self.database.list_papers()
                for alias in self.database.source_aliases(paper.id)
                if alias["source_path"] not in current_source_hashes
            )
        canonical, aliases_by_hash = _deduplicate_sources(sources, self.config.paths.root)
        report.duplicates = sum(len(items) for items in aliases_by_hash.values())
        full_reconciliation = not patterns and limit is None and not source_snapshot_incomplete
        if source_snapshot_incomplete:
            report.warnings.append(
                "Corpus retirement was disabled because one or more sources could not "
                "be discovered or hashed completely."
            )

        if patterns:
            canonical = [
                source
                for source in canonical
                if any(
                    fnmatch.fnmatch(
                        _relative(group_source.path, self.config.paths.root),
                        pattern,
                    )
                    or fnmatch.fnmatch(group_source.path.name, pattern)
                    for pattern in patterns
                    for group_source in (
                        source,
                        *aliases_by_hash.get(source.content_hash, []),
                    )
                )
            ]
        if limit is not None:
            if limit < 0:
                raise ValueError("limit must be non-negative")
            canonical = canonical[:limit]

        records = _record_lookup(curated)
        occupied = {paper.id for paper in self.database.list_papers()}
        changed_paper_ids: set[str] = set()

        def notes_for_paper(paper_id: str) -> list[str]:
            if source_snapshot_incomplete:
                return self._stored_notes_for(paper_id)
            return curated.notes_for(paper_id)

        for number, source in enumerate(canonical, start=1):
            source_path = _relative(source.path, self.config.paths.root)
            duplicate_sources = aliases_by_hash.get(source.content_hash, [])
            alias_rows = [
                SourceDocument(
                    path=Path(_relative(alias.path, self.config.paths.root)),
                    source_kind=alias.source_kind,
                    content_hash=alias.content_hash,
                )
                for alias in duplicate_sources
            ]
            source_group = [source, *duplicate_sources]
            try:
                if any(sha256_file(item.path) != item.content_hash for item in source_group):
                    raise RuntimeError(
                        "source bytes changed after discovery; rerun ingestion for a stable snapshot"
                    )
            except Exception as exc:
                if isinstance(exc, MemoryError):
                    raise
                report.failed += 1
                report.failures.append(
                    IngestFailure(source_path=source_path, stage="source_snapshot", error=str(exc))
                )
                self.database.record_failure(
                    source_path,
                    "source_snapshot",
                    str(exc),
                    content_hash=source.content_hash,
                )
                continue
            moving_paths = {source_path, *(str(alias.path) for alias in alias_rows)}
            prior_owners = {
                owner.id: owner
                for path in moving_paths
                if (owner := self.database.find_paper_by_source(path)) is not None
            }
            unchanged_existing = (
                self.database.find_paper_by_source(source_path)
                if not force and self.database.is_unchanged(source_path, source.content_hash)
                else None
            )
            requires_reprocessing = (
                unchanged_existing is not None
                and not self.database.paper_hierarchy_complete(unchanged_existing.id)
            )
            if requires_reprocessing:
                report.warnings.append(
                    f"{source_path}: stored hierarchy is incomplete; reprocessing the source."
                )
            if unchanged_existing is not None and not requires_reprocessing:
                existing = unchanged_existing
                if existing is not None:
                    for alias in alias_rows:
                        if not self.database.is_unchanged(alias.path, alias.content_hash):
                            self.database.add_source_alias(
                                existing.id,
                                alias.path,
                                content_hash=alias.content_hash,
                                source_kind=alias.source_kind,
                            )
                    for displaced in prior_owners.values():
                        if displaced.id == existing.id:
                            continue
                        retired = self._reconcile_displaced_paper(
                            displaced,
                            current_source_hashes,
                            curated,
                            notes_override=notes_for_paper(displaced.id),
                            uncertain_source_paths=uncertain_source_paths,
                        )
                        if retired:
                            occupied.discard(displaced.id)
                        changed_paper_ids.add(displaced.id)
                if existing is not None:
                    notes = notes_for_paper(existing.id)
                    sections = self.database.get_sections(existing.id)
                    card = build_research_card(existing, sections, notes)
                    card_path = self.config.paths.cards / f"{existing.id}.json"
                    try:
                        _assert_card_target_safe(card_path, existing.id, self.database)
                        write_research_card(
                            card_path,
                            card,
                        )
                    except Exception as exc:
                        if isinstance(exc, MemoryError):
                            raise
                        LOGGER.exception("Failed to write research card for %s", source_path)
                        report.failed += 1
                        failure = IngestFailure(
                            source_path=source_path,
                            stage="research_card",
                            error=str(exc),
                        )
                        report.failures.append(failure)
                        self.database.record_failure(
                            source_path,
                            "research_card",
                            str(exc),
                            content_hash=source.content_hash,
                        )
                        continue
                embedding_repaired = False
                rechunked = False
                if rechunk and existing is not None:
                    try:
                        stored_chunks = self.database.get_chunks(existing.id)
                        rebuilt_chunks = chunk_sections(sections, self.config.chunks)
                        if not rebuilt_chunks:
                            raise RuntimeError("chunker produced no usable chunks")
                        section_order_by_id = {
                            section.id: section.section_order
                            for section in sections
                            if section.id is not None
                        }

                        def signature(chunks, section_orders):
                            return [
                                (
                                    chunk.chunk_index,
                                    chunk.heading_path,
                                    chunk.text,
                                    chunk.token_count,
                                    chunk.page_start,
                                    chunk.page_end,
                                    (
                                        chunk.section_index
                                        if chunk.section_index is not None
                                        else section_orders.get(chunk.section_id)
                                    ),
                                )
                                for chunk in chunks
                            ]

                        if signature(
                            stored_chunks, section_order_by_id
                        ) != signature(rebuilt_chunks, section_order_by_id):
                            prepared_embedding = None
                            if embeddings:
                                prepared_embedding = self._prepare_paper_embeddings(
                                    existing,
                                    sections,
                                    rebuilt_chunks,
                                    notes,
                                )
                                self._guard_production_embeddings(
                                    prepared_embedding[0],
                                    prepared_embedding[1],
                                    protected_production_fingerprint,
                                )
                            before_commit = (
                                partial(
                                    self._commit_prepared_paper_artifacts,
                                    existing,
                                    sections,
                                    rebuilt_chunks,
                                    notes,
                                    prepared_embedding,
                                    None,
                                    None,
                                    "",
                                )
                                if prepared_embedding is not None
                                else None
                            )
                            self.database.replace_chunks_for_paper(
                                existing.id,
                                rebuilt_chunks,
                                before_commit=before_commit,
                            )
                            rechunked = True
                            LOGGER.info(
                                "Rechunked unchanged source: %s (%d chunks)",
                                existing.id,
                                len(rebuilt_chunks),
                            )
                    except Exception as exc:
                        LOGGER.exception("Failed to rechunk unchanged source %s", source_path)
                        report.failed += 1
                        report.failures.append(
                            IngestFailure(
                                source_path=source_path,
                                stage="rechunk",
                                error=str(exc),
                            )
                        )
                        self.database.record_failure(
                            source_path,
                            "rechunk",
                            str(exc),
                            content_hash=source.content_hash,
                        )
                        if isinstance(exc, MemoryError):
                            raise
                        continue
                if embeddings and existing is not None:
                    if not self._embedding_is_current(existing, notes):
                        try:
                            chunks = self.database.get_chunks(existing.id)
                            if not sections or not chunks:
                                raise RuntimeError(
                                    "stored paper hierarchy is incomplete; force re-ingestion is required"
                                )
                            model_name, fingerprint = self._embed_paper(
                                existing,
                                sections,
                                chunks,
                                notes,
                                protected_production_fingerprint=(protected_production_fingerprint),
                            )
                            self._record_embedding_state(
                                existing,
                                notes,
                                model_name=model_name,
                                model_fingerprint=fingerprint,
                            )
                            changed_paper_ids.add(existing.id)
                            embedding_repaired = True
                            LOGGER.info("Embedded unchanged source: %s", existing.id)
                        except Exception as exc:
                            LOGGER.exception("Failed to embed unchanged source %s", source_path)
                            report.failed += 1
                            report.failures.append(
                                IngestFailure(
                                    source_path=source_path,
                                    stage="embedding",
                                    error=str(exc),
                                )
                            )
                            self.database.record_failure(
                                source_path,
                                "embedding",
                                str(exc),
                                content_hash=source.content_hash,
                            )
                            if isinstance(exc, MemoryError):
                                raise
                            continue
                try:
                    if any(sha256_file(item.path) != item.content_hash for item in source_group):
                        raise RuntimeError(
                            "source bytes changed during ingestion; rerun for a stable snapshot"
                        )
                except Exception as exc:
                    if isinstance(exc, MemoryError):
                        raise
                    report.failed += 1
                    report.failures.append(
                        IngestFailure(
                            source_path=source_path,
                            stage="source_snapshot",
                            error=str(exc),
                        )
                    )
                    self.database.record_failure(
                        source_path,
                        "source_snapshot",
                        str(exc),
                        content_hash=source.content_hash,
                    )
                    continue
                for item in source_group:
                    self.database.clear_failures(_relative(item.path, self.config.paths.root))
                if embedding_repaired or rechunked:
                    report.indexed += 1
                else:
                    report.skipped += 1
                continue

            exact_duplicate = self.database.find_paper_by_hash(source.content_hash)
            if not force and not requires_reprocessing and exact_duplicate is not None:
                self.database.add_source_alias(
                    exact_duplicate.id,
                    source_path,
                    content_hash=source.content_hash,
                    source_kind=source.source_kind,
                )
                for alias in alias_rows:
                    self.database.add_source_alias(
                        exact_duplicate.id,
                        alias.path,
                        content_hash=alias.content_hash,
                        source_kind=alias.source_kind,
                    )
                for displaced in prior_owners.values():
                    if displaced.id == exact_duplicate.id:
                        continue
                    retired = self._reconcile_displaced_paper(
                        displaced,
                        current_source_hashes,
                        curated,
                        notes_override=notes_for_paper(displaced.id),
                        uncertain_source_paths=uncertain_source_paths,
                    )
                    if retired:
                        occupied.discard(displaced.id)
                    changed_paper_ids.add(displaced.id)
                for item in source_group:
                    self.database.clear_failures(_relative(item.path, self.config.paths.root))
                if not duplicate_sources:
                    report.duplicates += 1
                report.skipped += 1
                continue

            staged_markdown: Path | None = None
            generated_path: Path | None = None
            generated_existed = False
            prior_generated_text: str | None = None
            try:
                extracted = (
                    self.extractor.extract(source.path)
                    if source.source_kind == "pdf"
                    else extract_markdown_reference(source.path)
                )
                artifact_key = _artifact_key_for_source(
                    curated,
                    source,
                    self.config.paths.root,
                    source_inventory,
                    artifact_roots=self.config.paths.pdf_roots,
                )
                catalog_id = curated.artifact_to_paper_id.get(artifact_key)
                paper_id = stable_paper_id(
                    source.path,
                    catalog_id=catalog_id,
                    title=extracted.title,
                    authors=extracted.authors,
                    year=extracted.year,
                    content_hash=source.content_hash,
                )
                existing_by_source = self.database.find_paper_by_source(source_path)
                if existing_by_source is not None:
                    retaining_old_source = any(
                        path not in moving_paths
                        and (
                            current_source_hashes.get(path) == existing_by_source.content_hash
                            or path in uncertain_source_paths
                        )
                        for path in (
                            alias["source_path"]
                            for alias in self.database.source_aliases(existing_by_source.id)
                        )
                    )
                    if (
                        existing_by_source.content_hash == source.content_hash
                        or not retaining_old_source
                    ):
                        paper_id = existing_by_source.id
                    else:
                        existing_by_source = None
                if existing_by_source is None and paper_id in occupied:
                    existing_id = self.database.get_paper(paper_id)
                    if existing_id is None or existing_id.content_hash != source.content_hash:
                        paper_id = unique_paper_id(paper_id, source.content_hash, occupied)
                record = next(
                    (
                        item
                        for item in curated.records
                        if artifact_key in item.artifacts
                        or (
                            "/" not in artifact_key
                            and source.path.name
                            and source.path.name in {Path(name).name for name in item.artifacts}
                        )
                    ),
                    records.get(catalog_id or paper_id),
                )
                catalog_title = _catalog_title(record)
                catalog_authors = _catalog_authors(record)
                title = (
                    extracted.title
                    if _usable_title(extracted.title, source.path)
                    else catalog_title or _fallback_title(source.path)
                )
                # Corpus filenames are curated and consistently carry publication
                # years; prefer them over PDF creation-tool metadata.
                year_match = YEAR_RE.search(f"{source.path.stem} {catalog_title}")
                year = int(year_match.group(1)) if year_match else extracted.year
                abstract = extracted.abstract or _extract_abstract(extracted.markdown)
                if source.source_kind == "pdf":
                    generated_path = self.config.paths.generated_markdown / f"{paper_id}.md"
                    markdown_path = _relative(generated_path, self.config.paths.root)
                else:
                    generated_path = None
                    markdown_path = source_path
                paper = Paper(
                    id=paper_id,
                    title=title,
                    authors=(
                        extracted.authors
                        if _usable_authors(extracted.authors)
                        else catalog_authors or extracted.authors
                    ),
                    year=year,
                    doi=extracted.doi,
                    abstract=abstract,
                    source_path=source_path,
                    source_kind=source.source_kind,
                    markdown_path=markdown_path,
                    content_hash=source.content_hash,
                    extraction_backend=extracted.backend,
                )
                sections = parse_sections(extracted.markdown, paper_id, title)
                if not sections:
                    raise RuntimeError("section parser produced no usable sections")
                chunks = chunk_sections(sections, self.config.chunks)
                if not chunks:
                    raise RuntimeError("chunker produced no usable chunks")
                if any(sha256_file(item.path) != item.content_hash for item in source_group):
                    raise RuntimeError(
                        "source bytes changed during extraction; rerun for a stable snapshot"
                    )
                notes = notes_for_paper(paper_id)
                prepared_embedding = None
                if embeddings:
                    prepared_embedding = self._prepare_paper_embeddings(
                        paper,
                        sections,
                        chunks,
                        notes,
                    )
                    self._guard_production_embeddings(
                        prepared_embedding[0],
                        prepared_embedding[1],
                        protected_production_fingerprint,
                    )
                if generated_path is not None:
                    _assert_markdown_target_safe(
                        generated_path,
                        paper_id,
                        extracted.markdown,
                        self.database,
                        self.config.paths.root,
                        set(current_source_hashes),
                    )
                    generated_existed = generated_path.exists()
                    if generated_existed:
                        prior_generated_text = generated_path.read_text(encoding="utf-8")
                staged_markdown = (
                    _stage_text(generated_path, extracted.markdown)
                    if generated_path is not None
                    else None
                )
                card_path = self.config.paths.cards / f"{paper_id}.json"
                _assert_card_target_safe(card_path, paper_id, self.database)

                before_commit = (
                    partial(
                        self._commit_prepared_paper_artifacts,
                        paper,
                        sections,
                        chunks,
                        notes,
                        prepared_embedding,
                        staged_markdown,
                        generated_path,
                        extracted.markdown,
                    )
                    if prepared_embedding is not None or staged_markdown is not None
                    else None
                )
                self.database.replace_paper(
                    paper,
                    sections,
                    chunks,
                    aliases=alias_rows,
                    reconcile_aliases=True,
                    before_commit=before_commit,
                )
                if staged_markdown is not None and generated_path is not None:
                    staged_markdown = None
                card = build_research_card(paper, sections, notes)
                write_research_card(card_path, card)
                for item in source_group:
                    self.database.clear_failures(_relative(item.path, self.config.paths.root))
                for displaced in prior_owners.values():
                    if displaced.id == paper_id:
                        continue
                    retired = self._reconcile_displaced_paper(
                        displaced,
                        current_source_hashes,
                        curated,
                        notes_override=notes_for_paper(displaced.id),
                        uncertain_source_paths=uncertain_source_paths,
                    )
                    if retired:
                        occupied.discard(displaced.id)
                    changed_paper_ids.add(displaced.id)
                occupied.add(paper_id)
                changed_paper_ids.add(paper_id)
                report.indexed += 1
                report.warnings.extend(
                    f"{source_path}: {warning}" for warning in extracted.warnings
                )
                LOGGER.info(
                    "Indexed %d/%d: %s (%d sections / %d chunks via %s)",
                    number,
                    len(canonical),
                    paper_id,
                    len(sections),
                    len(chunks),
                    extracted.backend,
                )
            except Exception as exc:
                if staged_markdown is not None:
                    if not staged_markdown.exists() and generated_path is not None:
                        if generated_existed and prior_generated_text is not None:
                            rollback_stage = _stage_text(
                                generated_path,
                                prior_generated_text,
                            )
                            os.replace(rollback_stage, generated_path)
                        else:
                            generated_path.unlink(missing_ok=True)
                    staged_markdown.unlink(missing_ok=True)
                LOGGER.exception("Failed to ingest %s", source_path)
                report.failed += 1
                failure = IngestFailure(source_path=source_path, stage="ingest", error=str(exc))
                report.failures.append(failure)
                self.database.record_failure(
                    source_path,
                    "ingest",
                    str(exc),
                    content_hash=source.content_hash,
                )
                if isinstance(exc, MemoryError):
                    raise

        if full_reconciliation:
            discovered_paths = set(observed_source_paths)
            retired_count = 0
            for paper in self.database.list_papers():
                for alias in self.database.source_aliases(paper.id):
                    if alias["source_path"] not in discovered_paths:
                        self.database.remove_source_alias(alias["source_path"])
                if self._reconcile_displaced_paper(
                    paper,
                    current_source_hashes,
                    curated,
                    require_current_hash=False,
                    uncertain_source_paths=uncertain_source_paths,
                ):
                    retired_count += 1
                    changed_paper_ids.add(paper.id)
            for failure in self.database.list_failures():
                if (
                    not failure.source_path.startswith("__")
                    and failure.source_path not in discovered_paths
                ):
                    self.database.clear_failures(failure.source_path)
            if retired_count:
                report.warnings.append(
                    f"Retired {retired_count} paper(s) whose source files are no longer present."
                )

        previous_notes = {
            paper.id: self._stored_notes_for(paper.id) for paper in self.database.list_papers()
        }
        if not source_snapshot_incomplete:
            _relink_curated_to_stored_papers(
                curated,
                source_inventory,
                self.config.paths.root,
                self.database,
                catalog_artifact_to_record_id,
                artifact_roots=self.config.paths.pdf_roots,
            )
            current_notes = {
                paper.id: curated.notes_for(paper.id) for paper in self.database.list_papers()
            }
        else:
            current_notes = previous_notes
        note_changed_paper_ids = {
            paper_id
            for paper_id in previous_notes.keys() | current_notes.keys()
            if previous_notes.get(paper_id, []) != current_notes.get(paper_id, [])
        }

        curated_resolution_signature = _stable_digest(
            [
                {
                    "entry_type": entry.entry_type,
                    "heading_path": entry.heading_path,
                    "linked_paper_ids": entry.linked_paper_ids,
                    "source_line": entry.source_line,
                    "text": entry.text,
                }
                for entry in curated.entries
            ]
        )
        prior_index_hash = self.database.get_meta("curated_index_hash")
        prior_resolution = self.database.get_meta("curated_resolution_signature")
        effective_index_hash = (
            prior_index_hash
            if source_snapshot_incomplete and prior_index_hash is not None
            else index_hash
        )
        effective_resolution = (
            prior_resolution
            if source_snapshot_incomplete and prior_resolution is not None
            else curated_resolution_signature
        )
        curated_version = _stable_digest(
            {
                "index_hash": effective_index_hash,
                "resolution_signature": effective_resolution,
            }
        )
        replace_curated = not source_snapshot_incomplete and (
            force
            or changed_paper_ids
            or prior_index_hash != index_hash
            or prior_resolution != curated_resolution_signature
        )
        if replace_curated:
            try:
                prepared_curated = (
                    self._prepare_curated_embeddings(curated.entries) if embeddings else None
                )
                if prepared_curated is not None:
                    self._guard_production_embeddings(
                        prepared_curated[0],
                        prepared_curated[1],
                        protected_production_fingerprint,
                    )
                self.database.replace_curated_entries(
                    curated.entries,
                    before_commit=partial(
                        self._commit_curated_artifacts,
                        curated.entries,
                        prepared_curated,
                        curated_version,
                        index_hash,
                        curated_resolution_signature,
                    ),
                )
                self.database.clear_failures("__curated_index__")
            except Exception as exc:
                LOGGER.exception("Failed to atomically update the curated index")
                report.failed += 1
                failure = IngestFailure(
                    source_path="__curated_index__",
                    stage="curated_index",
                    error=str(exc),
                )
                report.failures.append(failure)
                self.database.record_failure(
                    failure.source_path,
                    failure.stage,
                    failure.error,
                )
                if isinstance(exc, MemoryError):
                    raise
                # Cards and final embedding reconciliation must remain aligned
                # with the last-good curated rows that survived the rollback.
                current_notes = previous_notes
                note_changed_paper_ids = set()
                effective_index_hash = prior_index_hash or ""
                effective_resolution = prior_resolution or ""
                curated_version = _stable_digest(
                    {
                        "index_hash": effective_index_hash,
                        "resolution_signature": effective_resolution,
                    }
                )
        for paper_id in sorted(note_changed_paper_ids):
            paper = self.database.get_paper(paper_id)
            if paper is None:
                continue
            sections = self.database.get_sections(paper_id)
            card_path = self.config.paths.cards / f"{paper_id}.json"
            try:
                _assert_card_target_safe(card_path, paper_id, self.database)
                write_research_card(
                    card_path,
                    build_research_card(paper, sections, current_notes.get(paper_id, [])),
                )
            except Exception as exc:
                if isinstance(exc, MemoryError):
                    raise
                LOGGER.exception("Failed to refresh research card for %s", paper_id)
                report.failed += 1
                failure = IngestFailure(
                    source_path=paper.source_path,
                    stage="research_card",
                    error=str(exc),
                )
                report.failures.append(failure)
                self.database.record_failure(
                    paper.source_path,
                    "research_card",
                    str(exc),
                    content_hash=paper.content_hash,
                )
        try:
            if not self.database.fts_complete():
                self.database.rebuild_fts()
                report.warnings.append("Rebuilt incomplete SQLite FTS mirrors.")
            self.database.clear_failures("__fts_consistency__")
        except Exception as exc:
            if isinstance(exc, MemoryError):
                raise
            LOGGER.exception("Failed to reconcile SQLite FTS mirrors")
            report.failed += 1
            failure = IngestFailure(
                source_path="__fts_consistency__",
                stage="fts_consistency",
                error=str(exc),
            )
            report.failures.append(failure)
            self.database.record_failure(
                failure.source_path,
                failure.stage,
                failure.error,
            )
        if embeddings:
            try:
                refreshed = self._reconcile_embedding_identity(
                    curated_version,
                    protected_production_fingerprint=protected_production_fingerprint,
                )
                if refreshed:
                    report.warnings.append(
                        f"Re-embedded {refreshed} paper(s) to restore one complete active "
                        "embedding fingerprint."
                    )
                self.database.clear_failures("__embedding_consistency__")
            except Exception as exc:
                LOGGER.exception("Failed to reconcile corpus embedding identity")
                report.failed += 1
                failure = IngestFailure(
                    source_path="__embedding_consistency__",
                    stage="embedding_consistency",
                    error=str(exc),
                )
                report.failures.append(failure)
                self.database.record_failure(
                    failure.source_path,
                    failure.stage,
                    failure.error,
                )
                if isinstance(exc, MemoryError):
                    raise
        snapshot_complete = full_reconciliation and report.failed == 0
        with self.database.transaction():
            if snapshot_complete:
                self.database.set_meta(
                    CORPUS_SOURCE_MANIFEST_KEY,
                    json.dumps(
                        build_source_manifest(self.config, index_hash, sources),
                        ensure_ascii=False,
                        sort_keys=True,
                        separators=(",", ":"),
                    ),
                )
            self.database.set_meta(
                CORPUS_SNAPSHOT_COMPLETE_KEY,
                "1" if snapshot_complete else "0",
            )
            self.database.set_meta(
                "last_ingest_report", json.dumps(report.to_dict(), ensure_ascii=False)
            )
        return report


def ingest_corpus(
    config: AppConfig,
    database: CorpusDatabase,
    **kwargs,
) -> IngestReport:
    return CorpusIngestor(config, database).ingest(**kwargs)
